-- Tạo cơ sở dữ liệu
DROP DATABASE IF EXISTS QuanLyBanHang;
CREATE DATABASE IF NOT EXISTS QuanLyBanHang;

USE QuanLyBanHang;


-- Tạo bảng KHACHHANG
CREATE TABLE IF NOT EXISTS KHACHHANG (
    MAKH VARCHAR(10) PRIMARY KEY,
    HOTEN NVARCHAR(100),
    DCHI NVARCHAR(255),
    SODT VARCHAR(15),
    NGSINH DATE,
    DOANHSO INT,
    NGDK DATE,
    LOAIKH TINYINT
);

-- Tạo bảng NHANVIEN
CREATE TABLE IF NOT EXISTS NHANVIEN (
    MANV VARCHAR(10) PRIMARY KEY,
    HOTEN NVARCHAR(100),
    NGVL DATE,
    SODT VARCHAR(15)
);

-- Tạo bảng SANPHAM
CREATE TABLE IF NOT EXISTS SANPHAM (
    MASP VARCHAR(10) PRIMARY KEY,
    TENSP NVARCHAR(100),
    DVT NVARCHAR(20),
    NUOCSX NVARCHAR(50),
    GIA INT,
    GHICHU VARCHAR(100)
);

-- Tạo bảng HOADON
CREATE TABLE IF NOT EXISTS HOADON (
    SOHD VARCHAR(10) PRIMARY KEY,
    NGHD DATE,
    MAKH VARCHAR(10),
    MANV VARCHAR(10),
    TRIGIA INT,
    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

-- Tạo bảng CTHD
CREATE TABLE IF NOT EXISTS CTHD (
    SOHD VARCHAR(10),
    MASP VARCHAR(10),
    SL INT,
    PRIMARY KEY (SOHD, MASP),
    FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD),
    FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
);

-- Thêm thuộc tính GHICHU cho SANPHAM
ALTER TABLE SANPHAM
ADD COLUMN GHICHU VARCHAR(20);

-- Thêm thuộc tính LOAIKH cho KHACHHANG
ALTER TABLE KHACHHANG
ADD COLUMN LOAIKH TINYINT;

-- Xóa thuộc tính GHICHU trong SANPHAM
ALTER TABLE KHACHHANG
DROP COLUMN LOAIKH;

-- Sửa kiểu dữ liệu của GHICHU trong SANPHAM
ALTER TABLE SANPHAM
MODIFY COLUMN GHICHU VARCHAR(100);

-- Xóa thuộc tính GHICHU trong SANPHAM
ALTER TABLE SANPHAM
DROP COLUMN GHICHU;

-- Định nghĩa LOAIKH trong KHACHHANG
ALTER TABLE KHACHHANG
ADD CONSTRAINT CK_LOAIKH CHECK (LOAIKH IN (1, 2, 3));

-- Đơn vị tính của sản phẩm chỉ có thể là (“cay”,”hop”,”cai”,”quyen”,”chuc”)
ALTER TABLE SANPHAM
ADD CONSTRAINT CK_DVT CHECK (DVT IN ('cay', 'hop', 'cai', 'quyen', 'chuc'));

-- Giá bán của sản phẩm từ 500 đồng trở lên
ALTER TABLE SANPHAM
ADD CONSTRAINT CK_GIA CHECK (GIA >= 500);

-- Ngày khách hàng đăng ký phải lớn hơn ngày sinh
ALTER TABLE KHACHHANG
ADD CONSTRAINT CK_NGDK_NGSINH CHECK (NGDK > NGSINH);

-- Ngày mua hàng của khách hàng thành viên phải lớn hơn hoặc bằng ngày đăng ký
ALTER TABLE HOADON
ADD CONSTRAINT CK_NGHD_NGDK CHECK (NGHD >= NGDK);

-- Ngày bán hàng của nhân viên phải lớn hơn hoặc bằng ngày vào làm
ALTER TABLE HOADON
ADD CONSTRAINT CK_NGHD_NGVL CHECK (NGHD >= NGVL);

-- Mỗi một hóa đơn phải có ít nhất một chi tiết hóa đơn
ALTER TABLE CTHD
ADD CONSTRAINT CK_SL_MIN CHECK (SL >= 1);

-- Trị giá của một hóa đơn là tổng thành tiền của các chi tiết hóa đơn
ALTER TABLE HOADON
ADD CONSTRAINT CK_TRIGIA CHECK (TRIGIA = (SELECT SUM(SL * GIA) FROM CTHD WHERE CTHD.SOHD = HOADON.SOHD));

-- Doanh số của một khách hàng là tổng trị giá các hóa đơn
ALTER TABLE KHACHHANG
ADD CONSTRAINT CK_DOANHSO CHECK (DOANHSO = (SELECT SUM(TRIGIA) FROM HOADON WHERE HOADON.MAKH = KHACHHANG.MAKH));


