-- Tìm số hóa đơn đã mua tất cả các sản phẩm do Singapore sản xuất:
SELECT COUNT(DISTINCT h.SOHD) AS SoHoaDon
FROM HOADON h
JOIN CTHD c ON h.SOHD = c.SOHD
JOIN SANPHAM s ON c.MASP = s.MASP
WHERE s.NUOCSX = 'Singapore'
GROUP BY h.SOHD
HAVING COUNT(DISTINCT s.MASP) = (SELECT COUNT(*) FROM SANPHAM WHERE NUOCSX = 'Singapore');

-- Có bao nhiêu hóa đơn không phải của khách hàng đăng ký thành viên mua:
SELECT COUNT(*) AS SoHoaDon
FROM HOADON h
WHERE h.MAKH IS NULL;


-- Có bao nhiêu sản phẩm khác nhau được bán ra trong năm 2006:
SELECT COUNT(DISTINCT c.MASP) AS SoSanPham
FROM CTHD c
JOIN HOADON h ON c.SOHD = h.SOHD
WHERE YEAR(h.NGHD) = 2006;

-- Cho biết trị giá hóa đơn cao nhất, thấp nhất:
SELECT MAX(TRIGIA) AS TrigiaCaoNhat, MIN(TRIGIA) AS TrigiaThapNhat
FROM HOADON;


-- Trị giá trung bình của tất cả các hóa đơn được bán ra trong năm 2006:
SELECT AVG(TRIGIA) AS TrigiaTrungBinh
FROM HOADON
WHERE YEAR(NGHD) = 2006;

-- Tính doanh thu bán hàng trong năm 2006:
SELECT SUM(TRIGIA) AS DoanhThu
FROM HOADON
WHERE YEAR(NGHD) = 2006;

USE QuanLyBanHang;

-- Tìm số hóa đơn có trị giá cao nhất trong năm 2006
SELECT HOADON.SOHD, HOADON.TRIGIA
FROM HOADON
WHERE YEAR(HOADON.NGHD) = 2006
ORDER BY HOADON.TRIGIA DESC
LIMIT 1;

USE QuanLyBanHang;

-- Tìm họ tên khách hàng đã mua hóa đơn có trị giá cao nhất trong năm 2006
SELECT KHACHHANG.HOTEN
FROM KHACHHANG
JOIN HOADON ON KHACHHANG.MAKH = HOADON.MAKH
WHERE HOADON.SOHD = (
    SELECT HOADON.SOHD
    FROM HOADON
    WHERE YEAR(HOADON.NGHD) = 2006
    ORDER BY HOADON.TRIGIA DESC
    LIMIT 1
);

-- In ra danh sách 3 khách hàng có doanh số cao nhất
SELECT KHACHHANG.MAKH, KHACHHANG.HOTEN, SUM(HOADON.TRIGIA) AS TONGDOANHSO
FROM KHACHHANG
JOIN HOADON ON KHACHHANG.MAKH = HOADON.MAKH
GROUP BY KHACHHANG.MAKH, KHACHHANG.HOTEN
ORDER BY TONGDOANHSO DESC
LIMIT 3;

-- In ra danh sách các sản phẩm có giá bán bằng 1 trong 3 mức giá cao nhất
SELECT MASP, TENSP
FROM SANPHAM
ORDER BY GIA DESC
LIMIT 3;

-- In ra danh sách các sản phẩm do "Thai Lan" sản xuất có giá bán bằng 1 trong 3 mức giá cao nhất
SELECT SANPHAM.MASP, SANPHAM.TENSP
FROM SANPHAM
JOIN CTHD ON SANPHAM.MASP = CTHD.MASP
JOIN HOADON ON CTHD.SOHD = HOADON.SOHD
WHERE SANPHAM.NUOCSX = 'Thai Lan'
ORDER BY SANPHAM.GIA DESC
LIMIT 3;

-- In ra danh sách các sản phẩm do "Trung Quoc" sản xuất có giá bán bằng 1 trong 3 mức giá cao nhất
SELECT SANPHAM.MASP, SANPHAM.TENSP
FROM SANPHAM
WHERE SANPHAM.NUOCSX = 'Trung Quoc'
ORDER BY SANPHAM.GIA DESC
LIMIT 3;

-- In ra danh sách 3 khách hàng có doanh số cao nhất
SELECT KHACHHANG.MAKH, KHACHHANG.HOTEN, SUM(HOADON.TRIGIA) AS TONGDOANHSO
FROM KHACHHANG
LEFT JOIN HOADON ON KHACHHANG.MAKH = HOADON.MAKH
GROUP BY KHACHHANG.MAKH, KHACHHANG.HOTEN
ORDER BY TONGDOANHSO DESC
LIMIT 3;


-- Tính tổng số sản phẩm do "Trung Quoc" sản xuất
SELECT COUNT(*) AS TONG_SAN_PHAM_TRUNG_QUOC
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc';

-- Tính tổng số sản phẩm của từng nước sản xuất
SELECT NUOCSX, COUNT(*) AS TONG_SAN_PHAM
FROM SANPHAM
GROUP BY NUOCSX;

-- Với từng nước sản xuất, tìm giá bán cao nhất, thấp nhất, trung bình của các sản phẩm
SELECT NUOCSX,
       MAX(GIA) AS GIA_CAO_NHAT,
       MIN(GIA) AS GIA_THAP_NHAT,
       AVG(GIA) AS GIA_TRUNG_BINH
FROM SANPHAM
GROUP BY NUOCSX;

-- Tính doanh thu bán hàng mỗi ngày
SELECT NGHD, SUM(TRIGIA) AS DOANHTHU
FROM HOADON
GROUP BY NGHD;

-- Tính tổng số lượng của từng sản phẩm bán ra trong tháng 10/2006
SELECT CTHD.MASP, SUM(CTHD.SL) AS TONG_SO_LUONG
FROM CTHD
JOIN HOADON ON CTHD.SOHD = HOADON.SOHD
WHERE DATE_FORMAT(HOADON.NGHD, '%Y-%m') = '2006-10'
GROUP BY CTHD.MASP;

-- Tính doanh thu bán hàng của từng tháng trong năm 2006
SELECT DATE_FORMAT(HOADON.NGHD, '%Y-%m') AS THANG,
       SUM(HOADON.TRIGIA) AS DOANH_THU
FROM HOADON
GROUP BY THANG;


-- Tìm hóa đơn có mua ít nhất 4 sản phẩm khác nhau
SELECT HOADON.SOHD
FROM HOADON
JOIN CTHD ON HOADON.SOHD = CTHD.SOHD
GROUP BY HOADON.SOHD
HAVING COUNT(DISTINCT CTHD.MASP) >= 4;

-- Tìm hóa đơn có mua 3 sản phẩm do "Viet Nam" sản xuất (3 sản phẩm khác nhau)
SELECT HOADON.SOHD
FROM HOADON
JOIN CTHD ON HOADON.SOHD = CTHD.SOHD
JOIN SANPHAM ON CTHD.MASP = SANPHAM.MASP
WHERE SANPHAM.NUOCSX = 'Viet Nam'
GROUP BY HOADON.SOHD
HAVING COUNT(DISTINCT CTHD.MASP) = 3;

-- Tìm khách hàng (MAKH, HOTEN) có số lần mua hàng nhiều nhất
SELECT KHACHHANG.MAKH, KHACHHANG.HOTEN, COUNT(HOADON.SOHD) AS SO_LAN_MUA
FROM KHACHHANG
JOIN HOADON ON KHACHHANG.MAKH = HOADON.MAKH
GROUP BY KHACHHANG.MAKH, KHACHHANG.HOTEN
ORDER BY SO_LAN_MUA DESC
LIMIT 1;

-- Tháng mấy trong năm 2006, doanh số bán hàng cao nhất
SELECT DATE_FORMAT(HOADON.NGHD, '%m') AS THANG,
       SUM(HOADON.TRIGIA) AS DOANH_SO
FROM HOADON
WHERE YEAR(HOADON.NGHD) = 2006
GROUP BY THANG
ORDER BY DOANH_SO DESC
LIMIT 1;

-- Tìm sản phẩm (MASP, TENSP) có tổng số lượng bán ra thấp nhất trong năm 2006
SELECT CTHD.MASP, SANPHAM.TENSP, SUM(CTHD.SL) AS TONG_SO_LUONG
FROM CTHD
JOIN SANPHAM ON CTHD.MASP = SANPHAM.MASP
JOIN HOADON ON CTHD.SOHD = HOADON.SOHD
WHERE YEAR(HOADON.NGHD) = 2006
GROUP BY CTHD.MASP, SANPHAM.TENSP
ORDER BY TONG_SO_LUONG ASC
LIMIT 1;

-- Mỗi nước sản xuất, tìm sản phẩm (MASP,TENSP) có giá bán cao nhất
SELECT SANPHAM.NUOCSX, SANPHAM.MASP, SANPHAM.TENSP, MAX(SANPHAM.GIA) AS GIA_BAN_CAO_NHAT
FROM SANPHAM
GROUP BY SANPHAM.NUOCSX, SANPHAM.MASP, SANPHAM.TENSP;

-- Tìm nước sản xuất sản xuất ít nhất 3 sản phẩm có giá bán khác nhau
SELECT SANPHAM.NUOCSX
FROM SANPHAM
GROUP BY SANPHAM.NUOCSX
HAVING COUNT(DISTINCT SANPHAM.GIA) >= 3;

-- Trong 10 khách hàng có doanh số cao nhất, tìm khách hàng có số lần mua hàng nhiều nhất
SELECT KHACHHANG.MAKH, KHACHHANG.HOTEN, COUNT(HOADON.SOHD) AS SO_LAN_MUA
FROM KHACHHANG
JOIN HOADON ON KHACHHANG.MAKH = HOADON.MAKH
GROUP BY KHACHHANG.MAKH, KHACHHANG.HOTEN
ORDER BY SUM(HOADON.TRIGIA) DESC
LIMIT 10;





